nameOverride: ""
fullnameOverride: ""

image:
  # -- repository to fetch images from
  repository: registry.k8s.io
  # -- default is the chart appVersion
  tag: ""

# -- allow User system:kube-scheduler to work with metrics and CRDs.
# primary usage is to replace default-scheduler with custom one
useForKubeSchedulerUser: false

scheduler:
  # -- deploy second scheduler as deployment
  enabled: false
  # -- path to scheduler image from repository
  image: scheduler-plugins/kube-scheduler
  imagePullPolicy: IfNotPresent
  # -- increase for HA mode
  replicaCount: 1
  # -- enable for HA mode
  leaderElect: false
  # -- Log level from 1 to 9
  verbosity: 1
  # -- Query per second limit of calls to apiserver
  qps: 50
  # -- 0 is default linear algorithm
  percentageOfNodesToScore: 0
  strategy:
    # -- Deployment update strategy type
    type: RollingUpdate
  # -- requests/limits for scheduler deployment
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 256Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  # -- affinity for deployment's pods
  affinity: {}

controller:
  # -- enable controller (needed for Coscheduling plugin)
  enabled: false
  # -- path to controller image from repository
  image: scheduler-plugins/controller
  imagePullPolicy: IfNotPresent
  # -- increase for HA mode
  replicaCount: 1
  strategy:
    # -- Deployment update strategy type
    type: RollingUpdate
  # -- requests/limits for controller deployment
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 256Mi
  # -- affinity for deployment's pods
  affinity: {}

priorityClassName: system-node-critical

tolerations: []

nodeSelector: {}

podAnnotations: {}

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL

# scheduler framework plugins @ignored
plugins:
  score:
    disabled:
      - name: NodeResourcesBalancedAllocation
      - name: NodeResourcesLeastAllocated
    enabled:
      - name: TargetLoadPacking
        weight: 1

# plugin specific args @ignored
pluginConfig:
  - name: RequestedToCapacityRatio
    args:
      shape:
        - utilization: 0
          score: 0
        - utilization: 100
          score: 10
      resources:
        - name: nvidia.com/gpu
          weight: 5
  - name: TargetLoadPacking
    args:
      defaultRequests:
        cpu: "100m"
      defaultRequestsMultiplier: "2"
      targetUtilization: 80
      # metricProvider: # By default, `metricProviderType` is `KubernetesMetricsServer`
      #   type: Prometheus
      #   address: http://prometheus-k8s.monitoring.svc.cluster.local:9090

schedulerConfig:
  # -- scheduler config apiversion (ref: https://kubernetes.io/docs/reference/scheduling/config/)
  apiVersion: kubescheduler.config.k8s.io/v1beta2
